version: '3.9'

services:
  web:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    hostname: web
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - my-network
    environment:
      - DATABASE_URL=postgresql://postgres:admin@localhost:5432/postgres?schema=public
      - NEXT_PUBLIC_JWT_SECRET_KEY=ae5e26624df41cac57d148688bd6406d2b25be8d43a71e061d98fb528aea5034
    depends_on:
      - postgres
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      - my-network
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    external: true

volumes:
  postgres_data:
    driver: local